package com.jdbcpg.todos;

public class FrmTask extends javax.swing.JFrame {

    public FrmTask() {
        initComponents();
                
        //custom initialization
        PG.url = "jdbc:postgresql://localhost:5432/todos";
        PG.username = "postgres";
        PG.password = "postgres";
        PG.className = "org.postgresql.Driver";
        
        buttonGroup1.add(rdoYes);
        buttonGroup1.add(rdoNo);
        rdoNo.setSelected(true);
        
        UIC.Frame.setDefault(this);
        
        String[] columns = {"ID","NAME","ISDONE"};
        String whereClause = "1=1";
        String[][] records = PG.executeDQL("task", columns, whereClause);
        UIC.Table.setModel(tblTask, records, columns);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTask = new javax.swing.JTable();
        btnNew = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtTask = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        rdoYes = new javax.swing.JRadioButton();
        rdoNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Todos by clydeatuic");

        tblTask.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTaskMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTask);

        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnChange.setText("Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Task ID");

        lblID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblID.setText("0");

        jLabel1.setText("Task Name");

        txtTask.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel2.setText("Task Status");

        rdoYes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoYes.setText("YES");

        rdoNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNo.setText("NO");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Note: Task name must have three or more letters.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTask)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(lblID))
                                    .addComponent(jLabel1))
                                .addGap(326, 326, 326)
                                .addComponent(rdoYes)
                                .addGap(18, 18, 18)
                                .addComponent(rdoNo)
                                .addGap(0, 19, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblID)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rdoYes)
                        .addComponent(rdoNo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnChange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChange, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTaskMouseClicked
        int id = UIC.Table.getSelectedRow(tblTask);
        
        String[] columns = {"ID","NAME","ISDONE"};
        String whereClause = "id=" + id;
        String[][] records = PG.executeDQL("task", columns, whereClause);

        lblID.setText(id+"");
        txtTask.setText(records[0][1]);
        if(records[0][2].equals("YES"))rdoYes.setSelected(true);
        else rdoNo.setSelected(true);

    }//GEN-LAST:event_tblTaskMouseClicked

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed
        int id = UIC.Table.getSelectedRow(tblTask);
        
        if(id!=0){
            String message = "Do you want to change this task?";
            String title = "Change Task";
            int option = javax.swing.JOptionPane.YES_NO_OPTION;
            int response = javax.swing.JOptionPane.showConfirmDialog(null, message, title, option);
            if(response==0){
                String task = txtTask.getText();
                String isdone = (rdoYes.isSelected())?"YES":"NO";
                Object[] values = {task, isdone, id};
                String query = "UPDATE task SET name=? ,isdone=? WHERE id=?";
                if(PG.executeDML(query, values)){
                    javax.swing.JOptionPane.showMessageDialog(null, "Task Changed!");

                    lblID.setText("0");
                    txtTask.setText("");
                    rdoNo.setSelected(true);
                    String[] columns = {"ID","NAME","ISDONE"};
                    String whereClause = "1=1";
                    String[][] records = PG.executeDQL("task", columns, whereClause);
                    UIC.Table.setModel(tblTask, records, columns);
                }
                else{
                    javax.swing.JOptionPane.showMessageDialog(null, "An error occured while changing task.");
                }            
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null, "Please select a row first!");
        }
    }//GEN-LAST:event_btnChangeActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int id = UIC.Table.getSelectedRow(tblTask);
        
        if(id!=0){
            String message = "Do you want to remove this task?";
            String title = "Remove Task";
            int option = javax.swing.JOptionPane.YES_NO_OPTION;
            int response = javax.swing.JOptionPane.showConfirmDialog(null, message, title, option);
            if(response==0){                
                Object[] values = {id};
                String query = "DELETE FROM task WHERE id=?";
                if(PG.executeDML(query, values)){
                    javax.swing.JOptionPane.showMessageDialog(null, "Task Removed!");

                    lblID.setText("0");
                    txtTask.setText("");
                    rdoNo.setSelected(true);
                    String[] columns = {"ID","NAME","ISDONE"};
                    String whereClause = "1=1";
                    String[][] records = PG.executeDQL("task", columns, whereClause);
                    UIC.Table.setModel(tblTask, records, columns);
                }
                else{
                    javax.swing.JOptionPane.showMessageDialog(null, "An error occured while removing task.");
                }            
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null, "Please select a row first!");
        }        
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        String task = txtTask.getText();
        if(task.length()>2){
            String isdone = (rdoYes.isSelected())?"YES":"NO";
            Object[] values = {task, isdone};
            String query = "INSERT INTO task (name, isdone) VALUES (?,?)";
            if(PG.executeDML(query, values)){
                javax.swing.JOptionPane.showMessageDialog(null, "New Task has been created!");

                lblID.setText("0");
                txtTask.setText("");
                rdoNo.setSelected(true);
                String[] columns = {"ID","NAME","ISDONE"};
                String whereClause = "1=1";
                String[][] records = PG.executeDQL("task", columns, whereClause);
                UIC.Table.setModel(tblTask, records, columns);            
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "An error occured while creating new task.");
            }
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(null, "Kindly follow task name requirement");
        }
        
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChange;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnRemove;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblID;
    private javax.swing.JRadioButton rdoNo;
    private javax.swing.JRadioButton rdoYes;
    private javax.swing.JTable tblTask;
    private javax.swing.JTextField txtTask;
    // End of variables declaration//GEN-END:variables
}
